import type { Metadata } from "next";
import { DirectionProvider } from "@/components/ui/direction";
import { yekanBakh } from "@/fonts";
import { SidebarProvider } from "@/components/ui/sidebar";
import { Toaster } from "@/components/ui/toast";
import { Inter } from "next/font/google";

import { AuthProvider } from "@/context/AuthProvider";
import { cn } from "@/lib/utils";
import "./globals.css";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

export const metadata: Metadata = {
  title: "بدو کادو",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl" className={cn("font-sans", yekanBakh.variable)}>
      <body className="bg-gradient-light">
        <AuthProvider>
          <DirectionProvider direction="rtl">
            <SidebarProvider>
              <div className="relative flex h-dvh w-full">
                <div className="p-5 h-full w-full overflow-auto hide-scrollbar bg-grad">
                  {children}
                </div>
              </div>
              <Toaster
              // toastOptions={{
              //   classNames: {
              //     toast: "cn-toast",
              //   },
              // }}
              // position="top-center"
              // closeButton
              />
            </SidebarProvider>
          </DirectionProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
