import type { Metadata } from "next";
import { DirectionProvider } from "@/components/ui/direction";
import { modam } from "@/fonts";
import { SidebarProvider } from "@/components/ui/sidebar";
import { Toaster } from "@/components/ui/toast";

import { AuthProvider } from "@/context/AuthProvider";
import { cn } from "@/lib/utils";
import "./globals.css";
import { ViewTransitions } from "next-view-transitions";

export const metadata: Metadata = {
  title: "بدو کادو",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl" className={cn(modam.variable)}>
      <body>
        <AuthProvider>
          <DirectionProvider direction="rtl">
            <SidebarProvider>
              <div className="relative flex h-dvh w-full">
                <div className="h-full w-full overflow-auto hide-scrollbar bg-grad">
                  <ViewTransitions>{children}</ViewTransitions>
                </div>
              </div>
              <Toaster
              // toastOptions={{
              //   classNames: {
              //     toast: "cn-toast",
              //   },
              // }}
              // position="top-center"
              // closeButton
              />
            </SidebarProvider>
          </DirectionProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
